### ISSUE TITLE
[EPIC] Improve usage for spot-price functionality as a module 

### ISSUE THREAD

**Issue by adrianriobo** [redhat-developer/mapt#255]
Beyond using directly `mapt` as a provisioning tool, it can be used as module to expose the `spot-price logic`, being used in that way another existing pieces of code can benefit of the logic.

- [x] #281
- [x] Review how to setup credentials to invoke the functions
- [x] Review types/func coding 
- [x] Expose func as cli operation?

**Comment by adrianriobo** [comment]
This is related to https://github.com/redhat-developer/mapt/issues/222 you can make use of it to get similar types once you get a type which matches the expectations.

If it does not apply just close as we will use this module instead.

**Comment by anjannath** [comment]
> This is related to [#222](https://github.com/redhat-developer/mapt/issues/222) you can make use of it to get similar types once you get a type which matches the expectations.
> 
> If it does not apply just close as we will use this module instead.

i did not explore this, (difficulity trying out resource manager graph queries) so currently using the Azure SDK to fetch all the VM SKUS and then filter based on its capabilities to find out the desired machine. (https://learn.microsoft.com/en-us/rest/api/compute/resource-skus/list?view=rest-compute-2024-07-01&tabs=Go#lists-all-available-resource-skus)

but this needs the families of VMs that offer nested virtualization, as from the SKU capabilities there's no field which mentions about nested virt support

**Comment by adrianriobo** [comment]
Closed by #284
